'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('country', [
      { name_ru: 'Россия', name_en: 'Russia' },
      { name_ru: 'Австралия', name_en: 'Australia' },
      { name_ru: 'Австрия', name_en: 'Austria' },
      { name_ru: 'Азербайджан', name_en: 'Azerbaijan' },
      { name_ru: 'Аландские острова', name_en: 'Åland Islands' },
      { name_ru: 'Албания', name_en: 'Albania' },
      { name_ru: 'Алжир', name_en: 'Algeria' },
      { name_ru: 'Американское Самоа', name_en: 'American Samoa' },
      { name_ru: 'Ангилья', name_en: 'Anguilla' },
      { name_ru: 'Ангола', name_en: 'Angola' },
      { name_ru: 'Андорра', name_en: 'Andorra' },
      { name_ru: 'Антарктида', name_en: 'Antarctica' },
      { name_ru: 'Антигуа и Барбуда', name_en: 'Antigua and Barbuda' },
      { name_ru: 'Аргентина', name_en: 'Argentina' },
      { name_ru: 'Армения', name_en: 'Armenia' },
      { name_ru: 'Аруба', name_en: 'Aruba' },
      { name_ru: 'Атолл Джонстон', name_en: 'Johnston Atoll' },
      { name_ru: 'Атолл Пальмира', name_en: 'Palmyra Atoll' },
      { name_ru: 'Афганистан', name_en: 'Afghanistan' },
      { name_ru: 'Багамские Острова', name_en: 'Bahamas, The' },
      { name_ru: 'Бангладеш', name_en: 'Bangladesh' },
      { name_ru: 'Барбадос', name_en: 'Barbados' },
      { name_ru: 'Бассас-да-Индия', name_en: 'Bassas da India' },
      { name_ru: 'Бахрейн', name_en: 'Bahrain' },
      { name_ru: 'Беларусь', name_en: 'Belarus' },
      { name_ru: 'Белиз', name_en: 'Belize' },
      { name_ru: 'Бельгия', name_en: 'Belgium' },
      { name_ru: 'Бенин', name_en: 'Benin' },
      { name_ru: 'Бермудские острова', name_en: 'Bermuda' },
      { name_ru: 'Болгария', name_en: 'Bulgaria' },
      { name_ru: 'Боливия', name_en: 'Bolivia' },
      { name_ru: 'Босния и Герцеговина', name_en: 'Bosnia and Herzegovina' },
      { name_ru: 'Ботсвана', name_en: 'Botswana' },
      { name_ru: 'Бразилия', name_en: 'Brazil' },
      { name_ru: 'Британская территория Индийского океана', name_en: 'British Indian Ocean Territory' },
      { name_ru: 'Британские Виргинские острова', name_en: 'British Virgin Islands' },
      { name_ru: 'Бруней', name_en: 'Brunei' },
      { name_ru: 'Буркина-Фасо', name_en: 'Burkina Faso' },
      { name_ru: 'Бурунди', name_en: 'Burundi' },
      { name_ru: 'Бутан', name_en: 'Bhutan' },
      { name_ru: 'Бывшая югославская Республика Македония', name_en: 'The Former Yugoslav Republic of Macedonia' },
      { name_ru: 'Вануату', name_en: 'Vanuatu' },
      { name_ru: 'Венгрия', name_en: 'Hungary' },
      { name_ru: 'Венесуэла', name_en: 'Venezuela' },
      { name_ru: 'Виргинские острова (США)', name_en: 'Virgin Islands (US)' },
      { name_ru: 'Реюньон', name_en: 'Reunion' },
      { name_ru: 'Восточный Тимор', name_en: 'East Timor' },
      { name_ru: 'Вьетнам', name_en: 'Vietnam' },
      { name_ru: 'Габон', name_en: 'Gabon' },
      { name_ru: 'Гаити', name_en: 'Haiti' },
      { name_ru: 'Гайана', name_en: 'Guyana' },
      { name_ru: 'Гамбия', name_en: 'Gambia, The' },
      { name_ru: 'Гана', name_en: 'Ghana' },
      { name_ru: 'Гваделупа', name_en: 'Guadeloupe' },
      { name_ru: 'Гватемала', name_en: 'Guatemala' },
      { name_ru: 'Гвинея', name_en: 'Guinea' },
      { name_ru: 'Гвинея-Бисау', name_en: 'Guinea-Bissau' },
      { name_ru: 'Германия', name_en: 'Germany' },
      { name_ru: 'Гернси', name_en: 'Guernsey' },
      { name_ru: 'Гибралтар', name_en: 'Gibraltar' },
      { name_ru: 'Гондурас', name_en: 'Honduras' },
      { name_ru: 'Гонконг', name_en: 'Hong Kong' },
      { name_ru: 'Гренада', name_en: 'Grenada' },
      { name_ru: 'Гренландия', name_en: 'Greenland' },
      { name_ru: 'Греция', name_en: 'Greece' },
      { name_ru: 'Грузия', name_en: 'Georgia' },
      { name_ru: 'Гуам', name_en: 'Guam' },
      { name_ru: 'Дания', name_en: 'Denmark' },
      { name_ru: 'Демократическая Республика Конго', name_en: 'Congo, Democratic Republic of the' },
      { name_ru: 'Джерси', name_en: 'Jersey' },
      { name_ru: 'Джибути', name_en: 'Djibouti' },
      { name_ru: 'Джордан', name_en: 'Jordan' },
      { name_ru: 'Доминика', name_en: 'Dominica' },
      { name_ru: 'Доминиканская Республика', name_en: 'Dominican Republic' },
      { name_ru: 'Египет', name_en: 'Egypt' },
      { name_ru: 'Замбия', name_en: 'Zambia' },
      { name_ru: 'Западная Сахара', name_en: 'Western Sahara' },
      { name_ru: 'Западный берег реки Иордан', name_en: 'West Bank' },
      { name_ru: 'Зимбабве', name_en: 'Zimbabwe' },
      { name_ru: 'Того', name_en: 'Togo' },
      { name_ru: 'Израиль', name_en: 'Israel' },
      { name_ru: 'Индия', name_en: 'India' },
      { name_ru: 'Индонезия', name_en: 'Indonesia' },
      { name_ru: 'Ирак', name_en: 'Iraq' },
      { name_ru: 'Иран', name_en: 'Iran' },
      { name_ru: 'Ирландия', name_en: 'Ireland' },
      { name_ru: 'Исландия', name_en: 'Iceland' },
      { name_ru: 'Испания', name_en: 'Spain' },
      { name_ru: 'Италия', name_en: 'Italy' },
      { name_ru: 'Йемен', name_en: 'Yemen' },
      { name_ru: 'Кабо-Верде', name_en: 'Cape Verde' },
      { name_ru: 'Казахстан', name_en: 'Kazakhstan' },
      { name_ru: 'Каймановы острова', name_en: 'Cayman Islands' },
      { name_ru: 'Камбоджа', name_en: 'Cambodia' },
      { name_ru: 'Камерун', name_en: 'Cameroon' },
      { name_ru: 'Канада', name_en: 'Canada' },
      { name_ru: 'Катар', name_en: 'Qatar' },
      { name_ru: 'Кения', name_en: 'Kenya' },
      { name_ru: 'Кипр', name_en: 'Cyprus' },
      { name_ru: 'Кирибати', name_en: 'Kiribati' },
      { name_ru: 'Китай', name_en: 'China' },
      { name_ru: 'Кокосовые (Килинг) острова', name_en: 'Cocos (Keeling) Islands' },
      { name_ru: 'Колумбия', name_en: 'Colombia' },
      { name_ru: 'Коморские острова', name_en: 'Comoros' },
      { name_ru: 'Косово', name_en: 'Kosovo' },
      { name_ru: 'Коста-Рика', name_en: 'Costa Rica' },
      { name_ru: 'Кот-д\'Ивуар', name_en: 'Cote d\'Ivoire' },
      { name_ru: 'Куба', name_en: 'Cuba' },
      { name_ru: 'Кувейт', name_en: 'Kuwait' },
      { name_ru: 'Кыргызстан', name_en: 'Kyrgyzstan' },
      { name_ru: 'Лаос', name_en: 'Laos' },
      { name_ru: 'Латвия', name_en: 'Latvia' },
      { name_ru: 'Лесото', name_en: 'Lesotho' },
      { name_ru: 'Либерия', name_en: 'Liberia' },
      { name_ru: 'Ливан', name_en: 'Lebanon' },
      { name_ru: 'Ливия', name_en: 'Libya' },
      { name_ru: 'Литва', name_en: 'Lithuania' },
      { name_ru: 'Лихтенштейн', name_en: 'Liechtenstein' },
      { name_ru: 'Люксембург', name_en: 'Luxembourg' },
      { name_ru: 'Маврикий', name_en: 'Mauritius' },
      { name_ru: 'Мавритания', name_en: 'Mauritania' },
      { name_ru: 'Мадагаскар', name_en: 'Madagascar' },
      { name_ru: 'Майотта', name_en: 'Mayotte' },
      { name_ru: 'Макао', name_en: 'Macau' },
      { name_ru: 'Малави', name_en: 'Malawi' },
      { name_ru: 'Малайзия', name_en: 'Malaysia' },
      { name_ru: 'Мали', name_en: 'Mali' },
      { name_ru: 'Мальдивы', name_en: 'Maldives' },
      { name_ru: 'Мальта', name_en: 'Malta' },
      { name_ru: 'Марокко', name_en: 'Morocco' },
      { name_ru: 'Мартиника', name_en: 'Martinique' },
      { name_ru: 'Маршалловы острова', name_en: 'Marshall Islands' },
      { name_ru: 'Мексика', name_en: 'Mexico' },
      { name_ru: 'Мидуэй острова', name_en: 'Midway Islands' },
      { name_ru: 'Микронезия, Федеративные Штаты', name_en: 'Micronesia, Federated States of' },
      { name_ru: 'Мозамбик', name_en: 'Mozambique' },
      { name_ru: 'Монако', name_en: 'Monaco' },
      { name_ru: 'Монголия', name_en: 'Mongolia' },
      { name_ru: 'Монтсеррат', name_en: 'Montserrat' },
      { name_ru: 'Мьянма', name_en: 'Myanmar' },
      { name_ru: 'Намибия', name_en: 'Namibia' },
      { name_ru: 'Науру', name_en: 'Nauru' },
      { name_ru: 'Непал', name_en: 'Nepal' },
      { name_ru: 'Нигер', name_en: 'Niger' },
      { name_ru: 'Нигерия', name_en: 'Nigeria' },
      { name_ru: 'Нидерландские Антильские острова', name_en: 'Netherlands Antilles' },
      { name_ru: 'Нидерланды', name_en: 'Netherlands' },
      { name_ru: 'Никарагуа', name_en: 'Nicaragua' },
      { name_ru: 'Ниуэ', name_en: 'Niue' },
      { name_ru: 'Ничейная земля', name_en: 'No Man\'s Land' },
      { name_ru: 'Новая Зеландия', name_en: 'New Zealand' },
      { name_ru: 'Новая Каледония', name_en: 'New Caledonia' },
      { name_ru: 'Норвегия', name_en: 'Norway' },
      { name_ru: 'Объединенное Королевство', name_en: 'United Kingdom' },
      { name_ru: 'Объединенные Арабские Эмираты', name_en: 'United Arab Emirates' },
      { name_ru: 'Оман', name_en: 'Oman' },
      { name_ru: 'Остров Бейкер', name_en: 'Baker Island' },
      { name_ru: 'Остров Буве', name_en: 'Bouvet Island' },
      { name_ru: 'Остров Джарвис', name_en: 'Jarvis Island' },
      { name_ru: 'Остров Европа', name_en: 'Europa Island' },
      { name_ru: 'Остров Клиппертон', name_en: 'Clipperton Island' },
      { name_ru: 'Остров Мэн', name_en: 'Isle of Man' },
      { name_ru: 'Остров Навасса', name_en: 'Navassa Island' },
      { name_ru: 'Остров Норфолк', name_en: 'Norfolk Island' },
      { name_ru: 'Остров Рождества', name_en: 'Christmas Island' },
      { name_ru: 'Остров Тромелин', name_en: 'Tromelin Island' },
      { name_ru: 'Остров Уэйк', name_en: 'Wake Island' },
      { name_ru: 'Остров Хоуленд', name_en: 'Howland Island' },
      { name_ru: 'Остров Хуан де Нова', name_en: 'Juan de Nova Island' },
      { name_ru: 'Острова Ашмор и Картье', name_en: 'Ashmore and Cartier Islands' },
      { name_ru: 'Острова Глориозо', name_en: 'Glorioso Islands' },
      { name_ru: 'Острова Кораллового моря', name_en: 'Coral Sea Islands' },
      { name_ru: 'Острова Кука', name_en: 'Cook Islands' },
      { name_ru: 'Острова Питкэрн', name_en: 'Pitcairn Islands' },
      { name_ru: 'Острова Спратли', name_en: 'Spratly Islands' },
      { name_ru: 'Острова Теркс и Кайкос', name_en: 'Turks and Caicos Islands' },
      { name_ru: 'Острова Херд и МакДональд', name_en: 'Heard Island and McDonald Islands' },
      { name_ru: 'Пакистан', name_en: 'Pakistan' },
      { name_ru: 'Палау', name_en: 'Palau' },
      { name_ru: 'Панама', name_en: 'Panama' },
      { name_ru: 'Папуа - Новая Гвинея', name_en: 'Papua New Guinea' },
      { name_ru: 'Парагвай', name_en: 'Paraguay' },
      { name_ru: 'Парасельские острова', name_en: 'Paracel Islands' },
      { name_ru: 'Перу', name_en: 'Peru' },
      { name_ru: 'Польша', name_en: 'Poland' },
      { name_ru: 'Португалия', name_en: 'Portugal' },
      { name_ru: 'Пуэрто-Рико', name_en: 'Puerto Rico' },
      { name_ru: 'Республика Конго', name_en: 'Congo, Republic of the' },
      { name_ru: 'Республика Молдова', name_en: 'Moldova, Republic of' },
      { name_ru: 'Риф Кингмена', name_en: 'Kingman Reef' },
      { name_ru: 'Руанда', name_en: 'Rwanda' },
      { name_ru: 'Румыния', name_en: 'Romania' },
      { name_ru: 'Самоа', name_en: 'Samoa' },
      { name_ru: 'Сан-Марино', name_en: 'San Marino' },
      { name_ru: 'Сан-Томе и Принсипи', name_en: 'Sao Tome and Principe' },
      { name_ru: 'Санкт-Люсия', name_en: 'Saint Lucia' },
      { name_ru: 'Саудовская Аравия', name_en: 'Saudi Arabia' },
      { name_ru: 'Свазиленд', name_en: 'Swaziland' },
      { name_ru: 'Святой Винсент и Гренадины', name_en: 'Saint Vincent and the Grenadines' },
      { name_ru: 'Святой Елены', name_en: 'Saint Helena' },
      { name_ru: 'Святой Мартин', name_en: 'Saint Martin' },
      { name_ru: 'Святой Престол (Ватикан)', name_en: 'Holy See (Vatican City)' },
      { name_ru: 'Северная Корея', name_en: 'Korea, North' },
      { name_ru: 'Северные Марианские острова', name_en: 'Northern Mariana Islands' },
      { name_ru: 'Сейшельские Острова', name_en: 'Seychelles' },
      { name_ru: 'Сектор Газа', name_en: 'Gaza Strip' },
      { name_ru: 'Сен-Пьер и Микелон', name_en: 'Saint Pierre and Miquelon' },
      { name_ru: 'Сенегал', name_en: 'Senegal' },
      { name_ru: 'Сент-Китс и Невис', name_en: 'Saint Kitts and Nevis' },
      { name_ru: 'Сербия и Черногория', name_en: 'Serbia and Montenegro' },
      { name_ru: 'Сербия', name_en: 'Serbia' },
      { name_ru: 'Сингапур', name_en: 'Singapore' },
      { name_ru: 'Сирийская Арабская Республика', name_en: 'Syrian Arab Republic' },
      { name_ru: 'Словакия', name_en: 'Slovakia' },
      { name_ru: 'Словения', name_en: 'Slovenia' },
      { name_ru: 'Соединенные Штаты Америки', name_en: 'United States' },
      { name_ru: 'Соломоновы острова', name_en: 'Solomon Islands' },
      { name_ru: 'Сомали', name_en: 'Somalia' },
      { name_ru: 'Суверенная базовая зона Декелия', name_en: 'Dhekelia Sovereign Base Area' },
      { name_ru: 'Судан', name_en: 'Sudan' },
      { name_ru: 'Суринам', name_en: 'Suriname' },
      { name_ru: 'Сьерра-Леоне', name_en: 'Sierra Leone' },
      { name_ru: 'Таджикистан', name_en: 'Tajikistan' },
      { name_ru: 'Таиланд', name_en: 'Thailand' },
      { name_ru: 'Тайвань', name_en: 'Taiwan' },
      { name_ru: 'Танзания, Объединенная Республика', name_en: 'Tanzania, United Republic of' },
      { name_ru: 'Токелау', name_en: 'Tokelau' },
      { name_ru: 'Тонга', name_en: 'Tonga' },
      { name_ru: 'Тринидад и Тобаго', name_en: 'Trinidad and Tobago' },
      { name_ru: 'Тувалу', name_en: 'Tuvalu' },
      { name_ru: 'Тунис', name_en: 'Tunisia' },
      { name_ru: 'Туркменистан', name_en: 'Turkmenistan' },
      { name_ru: 'Турция', name_en: 'Turkey' },
      { name_ru: 'Уганда', name_en: 'Uganda' },
      { name_ru: 'Узбекистан', name_en: 'Uzbekistan' },
      { name_ru: 'Украина', name_en: 'Ukraine' },
      { name_ru: 'Уоллис и Футуна', name_en: 'Wallis and Futuna' },
      { name_ru: 'Уругвай', name_en: 'Uruguay' },
      { name_ru: 'Фарерские острова', name_en: 'Faroe Islands' },
      { name_ru: 'Фиджи', name_en: 'Fiji' },
      { name_ru: 'Филиппины', name_en: 'Philippines' },
      { name_ru: 'Финляндия', name_en: 'Finland' },
      { name_ru: 'Фолклендские острова острова Мальвинские острова', name_en: 'Falkland Islands (Islas Malvinas)' },
      { name_ru: 'Франция', name_en: 'France' },
      { name_ru: 'Французская Гвиана', name_en: 'French Guiana' },
      { name_ru: 'Французская Полинезия', name_en: 'French Polynesia' },
      { name_ru: 'Французские южные и антарктические земли', name_en: 'French Southern and Antarctic Lands' },
      { name_ru: 'Хорватия', name_en: 'Croatia' },
      { name_ru: 'Центрально-Африканская Республика', name_en: 'Central African Republic' },
      { name_ru: 'Чад', name_en: 'Chad' },
      { name_ru: 'Черногория', name_en: 'Montenegro' },
      { name_ru: 'Чехия', name_en: 'Czech Republic' },
      { name_ru: 'Чили', name_en: 'Chile' },
      { name_ru: 'Швейцария', name_en: 'Switzerland' },
      { name_ru: 'Швеция', name_en: 'Sweden' },
      { name_ru: 'Шпицберген', name_en: 'Svalbard' },
      { name_ru: 'Шри-Ланка', name_en: 'Sri Lanka' },
      { name_ru: 'Эквадор', name_en: 'Ecuador' },
      { name_ru: 'Экваториальная Гвинея', name_en: 'Equatorial Guinea' },
      { name_ru: 'Эль Сальвадор', name_en: 'El Salvador' },
      { name_ru: 'Эритрея', name_en: 'Eritrea' },
      { name_ru: 'Эстония', name_en: 'Estonia' },
      { name_ru: 'Эфиопия', name_en: 'Ethiopia' },
      { name_ru: 'Южная Африка', name_en: 'South Africa' },
      { name_ru: 'Южная Георгия и острова', name_en: 'South Georgia and the Islands' },
      { name_ru: 'Южная Корея', name_en: 'Korea, South' },
      { name_ru: 'Ямайка', name_en: 'Jamaica' },
      { name_ru: 'Ян Майен', name_en: 'Jan Mayen' },
      { name_ru: 'Япония', name_en: 'Japan' }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('country', null, {});
  }
};
