export const academicDegreesRu = [
  'Кандидат архитектуры',
  'Кандидат биологических наук',
  'Кандидат ветеринарных наук',
  'Кандидат военных наук',
  'Кандидат географических наук',
  'Кандидат геолого-минералогических наук', 
  'Кандидат искусствоведения',
  'Кандидат исторических наук',
  'Кандидат культурологии',
  'Кандидат медицинских наук',
  'Кандидат педагогических наук',
  'Кандидат политических наук',
  'Кандидат психологических наук',
  'Кандидат сельскохозяйственных наук',
  'Кандидат социологических наук',
  'Кандидат теологических наук',
  'Кандидат технических наук',
  'Кандидат фармацевтических наук',
  'Кандидат физико-математических наук',
  'Кандидат филологических наук',
  'Кандидат философских наук',
  'Кандидат химических наук',
  'Кандидат экономических наук',
  'Кандидат юридических наук',
  'Доктор архитектуры',
  'Доктор биологических наук',
  'Доктор ветеринарных наук',
  'Доктор военных наук',
  'Доктор географических наук',
  'Доктор геолого-минералогических наук',
  'Доктор искусствоведения',
  'Доктор исторических наук',
  'Доктор культурологии', 
  'Доктор медицинских наук', 
  'Доктор педагогических наук',
  'Доктор политических наук',
  'Доктор психологических наук',
  'Доктор сельскохозяйственных наук',
  'Доктор социологических наук',
  'Доктор теологических наук',
  'Доктор технических наук', 
  'Доктор фармацевтических наук',
  'Доктор физико-математических наук',
  'Доктор филологических наук',
  'Доктор философских наук', 
  'Доктор химических наук',
  'Доктор экономических наук',
  'Доктор юридических наук'
];

export const academicDegreesEn = [
  'Candidate of Architecture',
  'Candidate of Biological Sciences',
  'Candidate of Veterinary Sciences',
  'Candidate of Military Sciences',
  'Candidate of Geographic Sciences',
  'Candidate of Geologo-Mineralogical Sciences',
  'Candidate of Art Criticism Sciences',
  'Candidate of Historical Sciences',
  'Candidate of Culturology',
  'Candidate of Medical Sciences',
  'Candidate of Pedagogic Sciences',
  'Candidate of Political Sciences',
  'Candidate of Psychological Sciences',
  'Candidate of Agricultural Sciences',
  'Candidate of Sociological Sciences',
  'Candidate of Theological Sciences',
  'Candidate of Engineering Sciences',
  'Candidate of Pharmaceutical Sciences',
  'Candidate of Physico-mathematical Sciences',
  'Candidate of Philological Sciences',
  'Candidate of Philosophical Sciences',
  'Candidate of Chemical Sciences',
  'Candidate of Economic Sciences',
  'Candidate of Juridical Sciences',
  'Doctor of Architecture',
  'Doctor of Biological Sciences',
  'Doctor of Veterinary Sciences',
  'Doctor of Military Sciences',
  'Doctor of Geographic Sciences',
  'Doctor of Geologo-Mineralogical Sciences',
  'Doctor of Art Criticism Sciences',
  'Doctor of Historical Sciences',
  'Doctor of Culturology Sciences',
  'Doctor of Medical Sciences',
  'Doctor of Pedagogic Sciences',
  'Doctor of Political Sciences',
  'Doctor of Psychological Sciences',
  'Doctor of Agricultural Sciences',
  'Doctor of Sociological Sciences',
  'Doctor of Theological Sciences',
  'Doctor of Engineering Sciences',
  'Doctor of Pharmaceutical Sciences',
  'Doctor of Physico-mathematical Sciences',
  'Doctor of Philological Sciences',
  'Doctor of Philosophical Sciences',
  'Doctor of Chemical Sciences',
  'Doctor of Economic Sciences',
  'Doctor of Juridical Sciences'
];

export const academicTitlesRu = [
  'Доцент',
  'Профессор'
];

export const academicTitlesEn = [
  'Docent',
  'Full Professor'
];
